name: CI/CD Pipeline

on:
  push:
    branches:
      - main_backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


  create_pull_request:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug repository state
        run: |
          git status
          git log --oneline
          git remote -v

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Build successful, creating PR to merge into main'
          title: 'Build successful, merge main_backend into main'
          body: 'Auto-generated pull request to merge main_backend into main after successful build.'
          head: main_backend
          base: main
          reviewers: dhruvpatel2308, Gruhit13

      - name: Get Pull Request URL
        id: get_pr_url
        run: |
          PR_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" | \
            jq -r '.[] | select(.head.ref == "main_backend" and .base.ref == "main") | .html_url')
          echo "PR_URL=${PR_URL}" >> $GITHUB_ENV

      - name: Output Pull Request URL
        run: echo "The Pull Request URL is ${{ env.PR_URL }}"
