name: Create Pull Request from main_backend to main

on:
  push:
    branches:
      - deploy_backend

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      

    - name: extrace git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

  
    - name: create pull request
      run: gh pr create -B main_backend -H deploy_backend --title 'Merge branch_to_merge into main_backend_branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
