name: LaunchHFBackend

on:
  push:
    branches: [deploy_backend]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Perform Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Add Remote
          env: 
            HF: ${{ secrets.HF }}
          run: git remote add space https://huggingface.co/spaces/gruhit-patel/deployment_app
        
        - name: Push to Space
          env: 
            HF: ${{ secrets.HF }}
          run: git push --force https://huggingface.co/spaces/gruhit-patel/deployment_app main