name: LaunchHFBackend

on:
  push:
    branches: [deploy_backend]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Perform Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Add Remote hugging face space
          env: 
            HF: ${{ secrets.HF }}
          run: git remote add space https://dpatel9923:$HF@huggingface.co/spaces/dpatel9923/house_price_prediction
        
        - name: Push to Space
          env: 
            HF: ${{ secrets.HF }}
          run: git push --force https://dpatel9923:$HF@huggingface.co/spaces/dpatel9923/house_price_prediction main