name: TestBackend

on:
  push:
    branches: main_backend

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
    - name: Perform checkout
      uses: actions/checkout@v2
    
    - name: Set up python to perform testing
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.0'

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
    
    - name: Run the testing
      run: pytest